### ISSUE TITLE
Cannot delete file / refresh cache

### ISSUE THREAD

**Issue by tieubao81** [dweidenfeld/plexdrive#328]
I delete a similar file in my google drive and it shows that it's gone.  But the plexdrive mount shows it's still there.  I manually try to delete it and I get these errors.  Is there a way to force plexdrive to scan for file changes?  The only way I've got it to work, is to delete the cache.bolt file in .plexdrive  but that's a pain to do every time.

[USERS/THANG/PLEXDRIVE] [2019-07-10 06:32] DEBUG  : Response
----------
&{404 Not Found 404 HTTP/2.0 2 0 map[Alt-Svc:[quic=":443"; ma=2592000; v="46,43,39"] Cache-Control:[private, max-age=0] Content-Length:[306] Content-Type:[application/json; charset=UTF-8] Date:[Wed, 10 Jul 2019 13:32:36 GMT] Expires:[Wed, 10 Jul 2019 13:32:36 GMT] Server:[UploadServer] Vary:[Origin X-Origin] X-Guploader-Uploadid:[AEnB2Ur5nU0lLhvBfiCmwvbMDw1noiXg83k1p8gCO0zVwwVCdbUwiF6qB4cFSuP9cL4x5FEsM0RSRQJokOau5PmJ0Z1fQESvVYlwsV7Pq8hfLsaAv-lCcoo]] 0xc0013c1c80 306 [] false false map[] 0xc0013af300 0xc0000dc210}
----------

[USERS/THANG/PLEXDRIVE] [2019-07-10 06:32] DEBUG  : Request
----------
&{GET https://www.googleapis.com/drive/v3/files/1lhLYTzCXb2Ms3UHGUZzH5xLXUBsDDc6E?alt=media HTTP/1.1 1 1 map[Range:[bytes=157286400-167772160]] <nil> <nil> 0 [] false www.googleapis.com map[] map[] <nil> map[]   <nil> <nil> <nil> <nil>}
----------

[USERS/THANG/PLEXDRIVE] [2019-07-10 06:32] DEBUG  : Response
----------
&{404 Not Found 404 HTTP/2.0 2 0 map[Alt-Svc:[quic=":443"; ma=2592000; v="46,43,39"] Cache-Control:[private, max-age=0] Content-Length:[306] Content-Type:[application/json; charset=UTF-8] Date:[Wed, 10 Jul 2019 13:32:36 GMT] Expires:[Wed, 10 Jul 2019 13:32:36 GMT] Server:[UploadServer] Vary:[Origin X-Origin] X-Guploader-Uploadid:[AEnB2UpJZzat9EafrgXOf0kjAP4QzlAaWsCXbgUUYECecGgT7f8a3RPGZuxZVCz2bEfAzeMP4Oi7SguyK4fbkj0S8TV-wdA5SOpOve8kITrznCX5GHMLtMQ]] 0xc001ee2040 306 [] false false map[] 0xc000f37800 0xc0000dc210}
----------

[USERS/THANG/PLEXDRIVE] [2019-07-10 06:32] DEBUG  : googleapi: Error 404: File not found: 1lhLYTzCXb2Ms3UHGUZzH5xLXUBsDDc6E., notFound
[USERS/THANG/PLEXDRIVE] [2019-07-10 06:32] WARNING: Could not delete object 1lhLYTzCXb2Ms3UHGUZzH5xLXUBsDDc6E (The Handmaid's Tale - S03E08 - Unfit WEBDL-720p.mkv) from API

**Comment by felixbuenemann** [comment]
Plexdrive should detect the deleted file, but it can take a couple of minutes.

Sometimes the cache can get out of sync, in that case removing the cache.bolt and restarting plexdrive is the solution.

If you delete a file again that no longer exists an error is expected, though it could probably be fixed in plexdrive to ignore 404 errors when deleting files.

I always mount plexdrive read-only and never tried deleting files, so I can't say how robust the delete feature is.

**Comment by tieubao81** [comment]
I'm still getting this problem, and the "work around" by deleting cache.bolt seems like a drag, as I have stuff updated constantly.  I delete the files on the google drive itself, and still came across plexdrive not properly updating it's db. For example

I deleted the file 720p file on google drive but it still lists in the directory.  I try to remove it via CLI but it still shows up.

bash-3.2$ ls -la
total 13499912
-rw-r--r--  1 thang  staff  2054831052 Sep 24 18:54 The Good Doctor - S03E01 - Disaster WEBDL-1080p.mkv
-rw-r--r--  1 thang  staff  1256503264 Oct  1 21:03 The Good Doctor - S03E02 - Debts WEBDL-1080p.mkv
-rw-r--r--  1 thang  staff   928569721 Oct  8 01:22 The Good Doctor - S03E03 - Claire HDTV-720p.mkv
-rw-r--r--  1 thang  staff  2672045930 Oct  8  2019 The Good Doctor - S03E03 - Claire WEBDL-1080p.mkv
bash-3.2$ rm -rf "The Good Doctor - S03E03 - Claire HDTV-720p.mkv"
bash-3.2$ ls -la
total 13499912
-rw-r--r--  1 thang  staff  2054831052 Sep 24 18:54 The Good Doctor - S03E01 - Disaster WEBDL-1080p.mkv
-rw-r--r--  1 thang  staff  1256503264 Oct  1 21:03 The Good Doctor - S03E02 - Debts WEBDL-1080p.mkv
-rw-r--r--  1 thang  staff   928569721 Oct  8 01:22 The Good Doctor - S03E03 - Claire HDTV-720p.mkv
-rw-r--r--  1 thang  staff  2672045930 Oct  8  2019 The Good Doctor - S03E03 - Claire WEBDL-1080p.mkv

PLEXDRIVE debug:
[USERS/THANG/PLEXDRIVE] [2019-10-08 07:08] DEBUG  : googleapi: Error 404: File not found: 1WiKK6SUeiyGQmzlaQ4fYNY8viAaVWqX5., notFound
[USERS/THANG/PLEXDRIVE] [2019-10-08 07:08] WARNING: Could not delete object 1WiKK6SUeiyGQmzlaQ4fYNY8viAaVWqX5 (The Good Doctor - S03E03 - Claire HDTV-720p.mkv) from API

Maybe my plexdrive db is too large?
bash-3.2$ ls -la
total 182032
drwxr--r--   5 thang  staff       170 Oct  5 12:15 .
drwxr-xr-x+ 27 thang  staff       918 Sep 28 15:30 ..
-rw-------   1 thang  staff  93192192 Oct  8 07:13 cache.bolt

**Comment by tieubao81** [comment]
I also mounted plexdrive read-only... then only remove media files from google drive web... yet the drive still shows the file present.  It is quite a pain in the rear to delete the cache.bolt file and restart every time I update a file from a lower resolution to a higher one.

Could you think of any other way to force plexdrive to scan for changes in it's directory structure?

**Comment by felixbuenemann** [comment]
I don't know why it's missing changes for you, it's working fine for me.

Maybe enabling debug logging using higher values for `-v` will give you hints what's going wrong.
