### ISSUE TITLE
Ability to specify cache and config directory location

### ISSUE THREAD

**Issue by jheyneman** [dweidenfeld/plexdrive#84]
Hello! 

I am successfully using plexdrive on an Ubuntu Server machine, but want to set it up on my QNAP.  I have specified a temporary directory for chunks and it worked correctly after accidentally filling the root storage.  

I am running into a different issue now...it took several days to build the cache for my GDrive, and afterward it worked as expected. However, when I rebooted my QNAP, the configuration directory, including the cache, was gone. I assume this has something to do with how the QNAP handles home directories, I think it overwrites them on boot.  Now I have to wait several days for it to rebuild, or copy the cache from my other machine.  While I can work-around this, it will end up getting removed if I have a power failure or have to reboot for some reason.  

I tried looking through the available flags and couldn't see anything that specified a directory other than temp and the config file path. 

Thanks!

**Comment by dany20mh** [comment]
@jheyneman 

As you said it yourself, 

For config you can use this : 
-c, --config string
    	The path to the configuration directory (default “~/.plexdrive")

For cache directory you can use this : 
-t, --temp string
    	Path to a temporary directory to store temporary data (default “/tmp")
 
As for deleting them, I don’t know why that happening to you, because if you define a correct folder and point them with those flag, they will stay there and they won’t get delete.
As for building cache, it’s weird, because mine is 60+ Tb and it takes maybe max 1 minutes to build the cache, and you are saying taking several days !!!

Make sure your setting is correct and you using it correctly.

**Comment by jheyneman** [comment]
Thanks for the reply @dany20mh. I guess I didn't realize the config string was the directory instead of specific filepath for the configuration. 

I tried copying over my cache from my other machine and it still restarted the First cache build process.  I'll try relocating my configuration and specifying it appropriately.  My GDrive is 18TB, but there are a lot of tiny files in there that aren't part of the Plex library.  I think there's an enhancement to specify a subfolder that is not yet complete that I'm waiting for. That's probably the reason for the slow caching.

**Comment by jheyneman** [comment]
Based on what I have written, this can be closed or deleted since it was the result of my stupidity.  :)

**Comment by jheyneman** [comment]
Although I do have another question if there is a quick answer.  I had to unmount plexdrive on my server and now it's rebuilding the cache from scratch again. What would cause this?

**Comment by Em31Et** [comment]
@dany20mh 
First cache for 60TB built in 1 minutes absolutely **IMPOSSIBLE**. 
You absolutely get banned if first built in 1 minutes.
The cache is still building in background. If you use -v 3, you will see the details.

**Comment by Em31Et** [comment]
@jheyneman 

The following sentence will still displayed after first build.
>  First cache build process started...
>  First cache build process finished!!

Is your WHOLE cache rebuild every time? or just saw the above sentence?

**Comment by jheyneman** [comment]
It seems to have finished quickly on my server. However, when I copied the cache to my QNAP, I figured I could start it up and have a pre-built cache, it did not work. It is definitely utilizing those files, but it has been running for a good hour now.

**Comment by Em31Et** [comment]
> However, when I copied the cache to my QNAP, I figured I could start it up and have a pre-built cache, it did not work. 
That means you cannot start plexdrive with the copied config and cache?

**Comment by jheyneman** [comment]
>That means you cannot start plexdrive with the copied config and cache?

Correct, it started rebuilding from scratch. I wonder why it doesn't utilize the copied cache, the files on Drive haven't changed.

**Comment by dany20mh** [comment]
@Em31Et 
Well I don’t have anything to lie to you, I have 60Tb of data on my Drive and I’ve been using this software from the beginning and because of some code changes and I delete my cache a few times and it build the cache in 1 minutes or so for me, I don’t know why you guys are struggling with it.

**Comment by Em31Et** [comment]
more user experience for your ref.
(https://www.reddit.com/r/PlexACD/comments/69u80p/plexdrive_mount_for_google_drive_with_cache/dha6vew/)

**Comment by Em31Et** [comment]
@jheyneman 
Including config? did you check permission?

**Comment by dany20mh** [comment]
@Em31Et 
I think it’s either you are confused or I’m confused.

We are talking about the cache file inside the config folder, which for me it’s only 18Mb (for the library of 60Tb) that I have, and making that it’s only taking 1 minutes.
But if we talking about Plex library, that will take for me 12 hours or so to scan the whole library (and that’s pretty much depend on your setting and your internet speed).

**Comment by Em31Et** [comment]
I think it is you.
The user experience in reddit and me is all talking about plexdrive cache (filename: cache)

**Comment by jheyneman** [comment]
Yes, file name of cache. On my QNAP, it takes 4-ish days to complete. On my Ubuntu Server (which has considerable horsepower) it completes in a day. I do have a ton of tiny files in there though. I think with the addition of being able to mount only a subfolder should resolve that problem though.

**Comment by dany20mh** [comment]
@jheyneman @Em31Et 
That’s definitely you two having problems somewhere else.

Because for me it doesn’t take that much to make that file and when I delete the file (and I run the app with -v 2) you can see it build the cache with, I don’t have good connection now, but I test it and just to show you two are wrong and it take 9 minutes this time.

```
[PLEXDRIVE] [2017-05-16 08:42] INFO   : First cache build process started…
[PLEXDRIVE] [2017-05-16 08:42] INFO   : Processed 460 items / deleted 460 items / updated 0 items
[PLEXDRIVE] [2017-05-16 08:42] INFO   : Processed 920 items / deleted 920 items / updated 0 items
[PLEXDRIVE] [2017-05-16 08:51] INFO   : Processed 105900 items / deleted 76039 items / updated 29861 items
[PLEXDRIVE] [2017-05-16 08:51] INFO   : First cache build process finished!
```
PS. I didn’t copy the whole code.
<img width="414" alt="screen shot 2017-05-16 at 7 38 24 pm" src="https://cloud.githubusercontent.com/assets/5872728/26132574/4282a224-3a6f-11e7-83a9-8b7b8963bae5.png">

**Comment by Em31Et** [comment]
@dany20mh 
>That’s definitely you two having problems somewhere else.
**NO** and this is not a problems
I have found more info from issue (#64). The cache speed depends on storage (SSD, HDD)

**Comment by dany20mh** [comment]
@Em31Et 

As for SSD and HDD, my computer is for 2015 which is iMac and it has HDD (APPLE HDD) and my cache save there (the cache file) and my temp folder is save on a 2TB HDD that I connect with USB2 to  my computer, so I don’t think there are that fast as SSD, so this is completely doesn’t depend on mine now.

**Comment by Em31Et** [comment]
@jheyneman 
But it still did not solve your issue.

In the meantime, maybe you can  use /dev/shm for the config dir (--config).
It may reduce your cache build time.
As found in (https://github.com/dweidenfeld/plexdrive/issues/64), the speed depends on the storage
It may reduce the time for rebuild whole cache on /dev/shm, but will destory on reboot.

**Comment by dany20mh** [comment]
@Em31Et 
I have nothing against you, but I just want to tell you that I’m not lying about having the cache ready in few minutes.

I’m not sure, but maybe because you guys using Linux and I’m using MacOS.
Even though when I was using the node-gdrive-fuse, that was taking a few minutes to build the cache too.
